### ISSUE TITLE
fail after fresh

### ISSUE THREAD

**Issue by l02162010** [gothinkster/golang-gin-realworld-example-app#12]
hello.go:9:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/articles" in any of:
	/Users/austin/go/src/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/articles (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/articles (from $GOROOT)
	/Users/austin/go/src/github.com/wangzitian0/golang-gin-starter-kit/articles (from $GOPATH)
hello.go:10:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/common" in any of:
	/Users/austin/go/src/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/common (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/common (from $GOROOT)
	/Users/austin/go/src/github.com/wangzitian0/golang-gin-starter-kit/common (from $GOPATH)
hello.go:11:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/users" in any of:
	/Users/austin/go/src/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/users (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/users (from $GOROOT)
	/Users/austin/go/src/github.com/wangzitian0/golang-gin-starter-kit/users (from $GOPATH)

**Comment by lulzmachine** [comment]
Also getting this. Any workarounds?
