### ISSUE TITLE
The ArticleFeed function is in ArticleRetrieve function

### ISSUE THREAD

**Issue by w4-hanggi** [gothinkster/golang-gin-realworld-example-app#18]
Is there better way handle this conflict for wildcard?

**Comment by wangzitian0** [comment]
I didn't get the point. Can you give more context?

**Comment by w4-hanggi** [comment]
```
func ArticleRetrieve(c *gin.Context) {
	slug := c.Param("slug")
	if slug == "feed" {
		ArticleFeed(c)
		return
	}
        ...
}
```

Like this code, due to the wildcard conflict, you have to add branch in the handler.

It looks bad, isn't it?

**Comment by wangzitian0** [comment]
For the branch:
In real world you will use elasticsearch? Relational database is not good at full-text index, we need reverse index?
For the frame work:
`request.com/balabala?slug=feed`, why have wildcard conflict.

**Comment by w4-hanggi** [comment]
router.GET("/:slug", ArticleRetrieve)
...

It's param, not query.

when the param of slug is "feed" go to ArticleFeed handler.

Please check it again.

**Comment by wangzitian0** [comment]
lol, I can not answer `https://github.com/gin-gonic/gin/issues?q=Wildcard+conflicts`
