### ISSUE TITLE
Cannot find package ".../wangzitian0/..."

### ISSUE THREAD

**Issue by adomokos** [gothinkster/golang-gin-realworld-example-app#5]
I'd like to test drive this project locally. I followed the instructions listed on the README.
Tried to run `go test -v ./... -cover`, but I received this error:

```shell
hello.go:9:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/articles" in any of:
	/Users/xyz/Programming/Go/projects/src/github.com/gothinkster/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/articles (vendor tree)
	/usr/local/opt/go/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/articles (from $GOROOT)
	/Users/xyz/Programming/Go/projects/src/github.com/wangzitian0/golang-gin-starter-kit/articles (from $GOPATH)
hello.go:10:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/common" in any of:
	/Users/xyz/Programming/Go/projects/src/github.com/gothinkster/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/common (vendor tree)
	/usr/local/opt/go/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/common (from $GOROOT)
	/Users/xyz/Programming/Go/projects/src/github.com/wangzitian0/golang-gin-starter-kit/common (from $GOPATH)
hello.go:11:2: cannot find package "github.com/wangzitian0/golang-gin-starter-kit/users" in any of:
	/Users/xyz/Programming/Go/projects/src/github.com/gothinkster/golang-gin-realworld-example-app/vendor/github.com/wangzitian0/golang-gin-starter-kit/users (vendor tree)
	/usr/local/opt/go/libexec/src/github.com/wangzitian0/golang-gin-starter-kit/users (from $GOROOT)
	/Users/xyz/Programming/Go/projects/src/github.com/wangzitian0/golang-gin-starter-kit/users (from $GOPATH)
```

Why is the `hello.go` file is referencing a different repo's model [here](https://github.com/gothinkster/golang-gin-realworld-example-app/blob/master/hello.go#L9)? Was it a incorrect merge? Am I missing something?

**Comment by adomokos** [comment]
I also pulled [wangzitian0's](https://github.com/wangzitian0/golang-gin-starter-kit) repo and that worked.

**Comment by adomokos** [comment]
I wonder what I did wrong with govendor, it never pulled in those dependencies.

Feel free to close this issue if you think it's not something you would be concerned about.

**Comment by mike-jianxin-mo** [comment]
I got the same problem and solved it by replacing all the "wangzitian0/golang-gin-starter-kit" to "github.com/golang-gin-realworld-example-app" in the application.

**Comment by BrutalSimplicity** [comment]
@wangzitian0 And how might one go about using a relative path. After a quick search, it appears that relative path imports aren't a thing in Go. All imports must start via the `$GOROOT`. Wouldn't it be better to rename the imports in this repository to the folder they would be cloned into by default "golang-gin-realworld-example-app"? That way this isn't an issue for people cloning the repository.

**Comment by g33klord** [comment]
this need to be merged asap.

This should be followed everytime contributing to a go project:  https://splice.com/blog/contributing-open-source-git-repositories-go/
