### ISSUE TITLE
question: about package name

### ISSUE THREAD

**Issue by thinkerou** [gothinkster/golang-gin-realworld-example-app#8]
Hi, @wangzitian0 @EricSimons 
I found the repo come from your personal repo https://github.com/wangzitian0/golang-gin-starter-kit, so, if your personal repo no longer maintain please mark as **warning** and redirect here.
Because I want to learn/use and commit pull request, but I don't know commit where, thanks!

BTW, if you permit, we should link the repo to gin readme.

**Comment by wangzitian** [comment]
Hi, @thinkerou ,
The codes of two repo are same now, doc has a little different. 
In general, gothinkster's repo is enough, but the management of golang package in this project was not very well yet, even some package path in gothinkster's repo was using my personal repo full path...
I think before the warning, we should:
1. Modify & check the import path in gothinkster's repo, better using relative path.
2. Make sure the two repo has no rely relationship..
3. Duplicate my personal repo.

Welcome to do the step1 &step2, thanks, hhhh

**Comment by wangzitian0** [comment]
@EricSimons Hi, Eric, 
Could you please help adding the travis CI app to https://github.com/gothinkster/golang-gin-realworld-example-app or add me to the gothinkster organization temporarily? I used to using my personal project to do that, for long term consideration, https://github.com/gothinkster/golang-gin-realworld-example-app/pull/10 was duplicating the rely relationship..
Thank you!

**Comment by wangzitian0** [comment]
@EricSimons Friendly ping.

**Comment by wangzitian0** [comment]
In general, the operation should be:
In https://github.com/marketplace/category/continuous-integration add `Codecov` and `Travis CI`.
In https://github.com/marketplace/travis-ci, click `Configure access `.
Then, click the configure of `Codecov` and `Travis CI`, give them permission.

Or add me to the gothinkster organization temporarily?
Thank you very much, Eric! @EricSimons
